"""Configuration for the non-destructive drone response timing simulator."""

WINDOW_WIDTH = 1100
WINDOW_HEIGHT = 760
FPS = 30
DT = 0.1

SCALE = 0.38
ORIGIN_X = WINDOW_WIDTH // 2
ORIGIN_Y = WINDOW_HEIGHT - 90
VECTOR_SECONDS = 5.0

LAUNCH_DELAY = 2.0
LAUNCH_INTERVAL = 3.0
SUCCESS_RADIUS = 8.0
PROTECTED_LINE_Y = 0.0
DETECTION_RANGE = 1100.0
INITIAL_INTERCEPTOR_SPEED = 60.0
INTERCEPTORS_PER_BALLOON = 6
INTERCEPTOR_MAX_TURN_RATE_DEG_PER_SEC = 20.0
INTERCEPTOR_MAX_FLIGHT_TIME = 180.0

DEFAULT_GUIDANCE_MODE = "sensor_delay"
MAX_GUIDANCE_LEAD_TIME = 12.0
SENSOR_DELAY_SECONDS = 1.0
TARGET_TRACK_RANGE = 650.0
TARGET_LOSS_HOLD_SECONDS = 4.0

DEFAULT_MANEUVER_MODE = "random"
MANEUVER_INTERVAL_RANGE = (3.0, 8.0)
MANEUVER_HORIZONTAL_FRACTION = 0.55

DEFAULT_TARGET_COUNT = 10
MIN_TARGET_COUNT = 1
MAX_TARGET_COUNT = 50
DEFAULT_RANDOM_SEED = 42
DEFAULT_STAGGERED_ARRIVAL = True
MAX_SPAWN_DELAY = 12.0
TARGET_START_X_RANGE = (-700.0, 700.0)
TARGET_START_Y_RANGE = (1350.0, 1650.0)
TARGET_SPEED_RANGE = (20.0, 30.0)
TARGET_HORIZONTAL_FRACTION = 0.35

BALLOON_TEMPLATES = [
    {"id": 1, "x": -500.0, "y": 0.0},
    {"id": 2, "x": 0.0, "y": 0.0},
    {"id": 3, "x": 500.0, "y": 0.0},
]
