"""Configuration for the non-destructive drone response timing simulator."""

WINDOW_WIDTH = 1100
WINDOW_HEIGHT = 760
FPS = 30
DT = 0.1

SCALE = 0.38
ORIGIN_X = WINDOW_WIDTH // 2
ORIGIN_Y = WINDOW_HEIGHT - 90
VECTOR_SECONDS = 5.0

LAUNCH_DELAY = 2.0
LAUNCH_INTERVAL = 3.0
SUCCESS_RADIUS = 8.0
FOB_LINE_Y = 0.0
BALLOON_PICKET_DISTANCE = 500.0
BALLOON_PICKET_Y = FOB_LINE_Y + BALLOON_PICKET_DISTANCE
PROTECTED_LINE_Y = FOB_LINE_Y
DETECTION_RANGE = 1100.0

GROUND_CUEING_ENABLED = True
GROUND_SENSOR_DETECTION_Y = 1450.0
GROUND_TRACK_DELAY = 1.0
GLOBAL_ASSIGNMENT_ENABLED = True
QUEUE_SCORE_WEIGHT = 1.0
INVENTORY_SCORE_WEIGHT = 8.0

INTERCEPTOR_TYPE = "small_delta_wing"
INTERCEPTOR_DROP_ANGLE_DEG = 10.0
INTERCEPTOR_STABILIZATION_TIME = 3.0
INITIAL_INTERCEPTOR_SPEED = 60.0
INTERCEPTORS_PER_BALLOON = 6
INTERCEPTOR_NORMAL_TURN_RATE_DEG_PER_SEC = 14.0
INTERCEPTOR_HARD_TURN_RATE_DEG_PER_SEC = 20.0
INTERCEPTOR_HARD_TURN_TRIGGER_DEG = 45.0
INTERCEPTOR_HARD_TURN_MAX_SECONDS = 2.0
INTERCEPTOR_HARD_TURN_COOLDOWN_SECONDS = 6.0
INTERCEPTOR_MAX_FLIGHT_TIME = 180.0

# Abstract onboard tracking model. These values drive only the simulated
# confidence/acquisition state and do not represent a real sensor implementation.
ONBOARD_TRACKING_ENABLED = True
ONBOARD_ACQUISITION_RANGE = 700.0
ONBOARD_INITIAL_CONFIDENCE = 0.45
ONBOARD_CONFIDENCE_GAIN_PER_SEC = 0.30
ONBOARD_CONFIDENCE_DECAY_PER_SEC = 0.22
ONBOARD_LOCK_THRESHOLD = 0.65
ONBOARD_LOSS_THRESHOLD = 0.25
ONBOARD_REACQUIRE_WINDOW_SECONDS = 5.0
ONBOARD_CLUTTER_RADIUS = 120.0
ONBOARD_CLUTTER_PENALTY_PER_TARGET = 0.06

DEFAULT_GUIDANCE_MODE = "sensor_delay"
MAX_GUIDANCE_LEAD_TIME = 12.0
SENSOR_DELAY_SECONDS = 1.0
TARGET_TRACK_RANGE = 650.0
TARGET_LOSS_HOLD_SECONDS = 4.0

DEFAULT_MANEUVER_MODE = "random"
MANEUVER_INTERVAL_RANGE = (3.0, 8.0)
MANEUVER_HORIZONTAL_FRACTION = 0.55

DEFAULT_TARGET_COUNT = 10
MIN_TARGET_COUNT = 1
MAX_TARGET_COUNT = 50
DEFAULT_RANDOM_SEED = 42
DEFAULT_STAGGERED_ARRIVAL = True
MAX_SPAWN_DELAY = 12.0
TARGET_START_X_RANGE = (-700.0, 700.0)
TARGET_START_Y_RANGE = (1350.0, 1650.0)
TARGET_SPEED_RANGE = (18.0, 25.0)
TARGET_HORIZONTAL_FRACTION = 0.35

BALLOON_TEMPLATES = [
    {"id": 1, "x": -750.0, "y": FOB_LINE_Y + 330.0},
    {"id": 2, "x": 0.0, "y": BALLOON_PICKET_Y},
    {"id": 3, "x": 750.0, "y": FOB_LINE_Y + 330.0},
]
